version: "3"


# to restore a dump from folder
# docker-compose exec -T mongo mongorestore /dump
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./dump:/dump/

  mongo-indexes:
    image: mongo
    container_name: mongo-indexes
    links:
      - mongo
    volumes:
      - ./scripts:/scripts
    command: mongo --host mongo /scripts/build-indexes.js
    depends_on:
      - mongo

  api:
    build:
      context: .
    ports:
      - "9000:9000"
    environment:
      DEBUG: "*,-body-parser*,-express*,-follow-redirects"
      key: my-dev-key
      mongoHost: mongo
    links:
      - mongo
    volumes:
      - ./bin:/app/bin
      - ./config:/app/config
      - ./endpoints:/app/endpoints
      - ./lib:/app/lib
      - ./models:/app/models
      - ./parsers:/app/parsers
      - ./routes:/app/routes
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    working_dir: /app
    command: npm run watch
